### ISSUE TITLE
Removal of Token Persistence

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#1664]
### Problem

Current API-M deployments utilize JWT access tokens since the required number of queries for the validation is much lesser than the opaque tokens. But due to the following use cases, a reference called the JTI is persisted at the token table for each generated access token.
- To revocate an access token before the actual expiry time.
- To use refresh token in refresh-grant flow

In large-scale deployments of WSO2 API Manager, this can cause a bottleneck in the persistence layer and result in reduced TPS for token generation. This can negatively impact the overall performance of the deployment. A solution is needed to improve TPS for token generation in these high-load scenarios.

### Solution

The proposed solution aims to improve token management by removing the persistence of tokens in the database.

### Affected Component

APIM

### Version

4.2.0

**Comment by chamilaadhi** [comment]
Initial POC was done by Dushani and it is documented in https://docs.google.com/document/d/1Owp_Ams5Y_xLX0xFk2t50rFCeNxL0T6CxIs4ITHTMc4/edit#

Following areas need to be handled
- [ ] Access Token Generation
- [ ] Refresh Token Generation
- [ ] Refresh Token Grant Type related changes
- [ ] Token Revocation
- [ ] Revocations due to internal events

**Comment by chamilaadhi** [comment]
Following are the PRs for Identitiy repo containing newly introduced interfaces

Access Token Generation https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2041 
Refresh Token Generation https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2042
Refresh Token Grant Type related changes  https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2043

**Comment by chamilaadhi** [comment]
Add new component for keymanager extension to add new code repo https://github.com/wso2-extensions/apim-km-wso2is/pull/96

**Comment by chamilaadhi** [comment]
New DB is introduced to store persistence related data

      CREATE TABLE IF NOT EXISTS AM_INVALID_TOKENS (
         UUID VARCHAR(255) NOT NULL,
         SIGNATURE VARCHAR(2048) NOT NULL,
         CONSUMER_KEY VARCHAR(255) NOT NULL,
         TOKEN_TYPE VARCHAR(15) NOT NULL,
         TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
         EXPIRY_TIMESTAMP BIGINT NOT NULL,
         PRIMARY KEY (UUID)
      ) ENGINE=InnoDB;

Need to add the following datasource in deployment.toml to point to this

      [[datasource]]
      id = "WSO2_PERSISTENCE_DB"
      url = "jdbc:mysql://localhost:3306/invalid_token_db?useSSL=false"
      username = "root"
      password = "Admin123"
      driver = "com.mysql.jdbc.Driver"
      validationQuery = "SELECT 1"
      pool_options.validationInterval = "30000"
      pool_options.defaultAutoCommit = "true"
      pool_options.maxActive = "50"
      pool_options.maxWait = "60000"
      pool_options.testOnBorrow = "true"


Add db util to access new db https://github.com/wso2-extensions/apim-km-wso2is/pull/97

**Comment by chamilaadhi** [comment]
identity-inbound-auth-oauth repo prs for master branch with new interfaces
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2054
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2055 
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2056

**Comment by chamilaadhi** [comment]
initial implementation for apim keymanager connectors  https://github.com/wso2-extensions/apim-km-wso2is/pull/100

**Comment by chamilaadhi** [comment]
In APIM, portals work with opaque tokens. This needs to be changed to JWT tokens. Currently, JWT tokens are not supported when invoking product APIs. JWT based implementation is introduced to Choreo but is not working with APIM. Currently working on getting this to work with APIM

**Comment by chamilaadhi** [comment]
Set the product apis to work with JWT tokens https://github.com/wso2/carbon-apimgt/pull/11976

**Comment by chamilaadhi** [comment]
Add cleanup mechanism to remove expired tokens https://github.com/wso2-extensions/apim-km-wso2is/commit/386ee3387837733c9915f26f041ba3aabb84c5d9

Created a doc with instruction on setting up https://docs.google.com/document/d/16uISJGhspJfQ31iYaAflwdoNNSRbJABbEdsBpt7EaII/edit

**Comment by dushaniw** [comment]
2023.11.06
Fixed the PR review comments in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2091

**Comment by dushaniw** [comment]
Following are the remaining tasks of the feature.

<google-sheets-html-origin><style type="text/css"></style>

- [ ] Fix PR comments
- [ ] Create design outline doc and send architecture mail
- [ ] Handle token introspection
- [ ] Handle userinfo endpoint
- [ ] Handle indirect revocations in refresh grant and token revocation
- [ ] Analyze impact of oauth2 tokens
- [ ] Handle oauth tokens parallely with a config
- [ ] Refactor connector code
- [ ] Refactor gateway validation code
- [ ] Smoke test
- [ ] Move connector code to IS connector
- [ ] Performance tests

**Comment by dushaniw** [comment]
While refactoring the connector code, came across following issues which need broader discussion before handling them

1. Impact to oauth cache as token persistence is removed.
2. Impact to token binding feature as we no longer have references to token/binding in database.
3. Impact to consented column in current access token table, and is consented value in AccessTokenDO.
4. Impact to current use of opaque token of customers
5. Impact to migration of current use of customized solutions for following cases
      - JWT persistence through custom issuer
      - revocation of old JWT token
      - use of both opaque and JWT at the same time

**Comment by dushaniw** [comment]
**Migration Impact**

The feature will be configurable, and it can be turned on if a user likes and the migration from old setup (old token tables) to new setup (new token tables) will be handled seamlessly. You cannot revert back to the old setup once you turn off the feature if you wish to use the old tokens. The custom implementation will be kept in the current IS-KM connector which will be released in parallel with future IS versions.

**Comment by dushaniw** [comment]
We had a review on the https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2176 and following were discussed as actions items:

1. Fix test failures.
2. Seamlessly handle both invalidated refresh and revoked tokens without premigration to new table.
3. Remove db check for expired or revoked tokens during revocation endpoint flow.
4. Re-visit the naming of rules for indirect token revoke events and analyze the capability following a similar approach to risk profile spec.
https://openid.net/specs/openid-risc-profile-specification-1_0.html#rfc.section.2.2
https://openid.net/specs/openid-sse-framework-1_0-01.html
https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#section-3.2.4-1
https://datatracker.ietf.org/doc/html/rfc8417
https://openid.net/specs/openid-caep-specification-1_0-01.html#rfc.section.3.3

**Comment by Lakith-Rambukkanage** [comment]
- [ ] https://github.com/wso2-enterprise/wso2-apim-internal/issues/4702

**Comment by dushaniw** [comment]
Update 20.10.2023

- Added support for entity_id and is_consented claims in JWT tokens and added support in IS-KM connector as well.
- Will be checking the token cache behavior next.

**Comment by dushaniw** [comment]
Update 2023.10.26

- Fixed token cache behavior.
- Refactored revocation processor and token provider.
- Will be refactoring the connector code along with following next.
- [ ] Seamlessly handle both invalidated refresh and revoked tokens without premigration to new table.
- [ ] Remove db check for expired or revoked tokens during revocation endpoint flow.

**Comment by dushaniw** [comment]
Update 2023.10.27

Fixed the code to work with migrated tokens by checking the old access token table.  Merged the fixes for identity code to handle consented claim in refresh token, entity_id claim for tokens and to fix issues in cache validation logic. More info can be found in PR description of https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2208.

Following are the next planned tasks.
- Refactor  current is-km connector code.
- Merge changes from Lakith for indirect user token revocations in https://github.com/wso2-extensions/apim-km-wso2is/pull/111.
- Polish up the overall is-km connector code and changes in https://github.com/wso2/carbon-apimgt/pull/12174.
- Write missing unit tests.
- Test with API-M usecases.
- Initiate discussion on the following missing claims for the access tokens which currently we store against the token in the DB.
     1. token_binding
     2. is_consented
     3. grant_type
     4. token_id
     5. tenant_id
     6. authorization_code

**Comment by dushaniw** [comment]
### Task List Updated as of 2023.11.04
✅ Check whether app updates, delete are revoking tokens in default IS case and non persistence case
🕐 Test scenarios in the Testing CheckList
- [x] Add java doc comments 
- [x] Refactor lakith’s APIM code
- [x] Connect with APIM code
- [x] Test IS-KM scenario + backend JWT
- [x] Refactor APIM code changes
- [ ] Define unit test cases
- [x] Define integration test cases
- [x] Prepare doc for IS discussion
- [x] Prepare doc for code review
- [ ] Write unit test cases
- [ ] Write integration test cases
- [x] Prepare and test db scripts for all databases

**To be discussed**
- [ ] Handle tenant delete events for token revocation

### Testing Checklist
**Tested scenarios**
✅ Internal user event for revocation + introspection
✅ Internal consumer app event for revocation + introspection
✅ Access token generation - password + client cred grants
✅ Refresh token generation - password grant
✅ Refresh grant handler basic scenarios
✅ Consented claim in refresh and access token generation + userinfo endpoint
✅ Refresh grant handler - error path for access token
✅ Refresh token (valid, invalid) + introspection endpoint
✅ Refresh grant handler - revoked refresh token
✅ Authorization code grant handler basic scenarios
✅ Token revocation direct access token + introspection + userinfo endpoint
✅ Token revocation direct refresh token + introspection + userinfo endpoint
✅ Internal userevent for revocation + client cred grant token + introspection endpoint
✅ Internal consumer app event for revocation + client cred grant token + introspection endpoint

**TODO**
- [x] Refresh grant handler - renew existing token = false
- [x] Refresh grant handler - opaque refresh token
- [x] Authorization code grant consented claim + userinfo endpoint
- [x] Authorization code grant cache behavior
- [x] Authorization code grant with id token
- [x] Implicit grant basic scenarios with consented claim + userinfo endpoint
- [x] Implicit grant basic scenarios with id token
- [x] Token introspection for opaque refresh tokens
- [x] Token revocation for opaque refresh tokens
- [x] Federated user + auth code grant + introspection + userinfo
- [x] JWT Bearer grant
- [ ] SAML Bearer grant

**Comment by dushaniw** [comment]
The pending items of the task are as follows :

- Add recently suggested changes to IS 
     - introduce new claim to keep token ID in JWT claims
- Run integration tests in IS
- Run performance tests used for IS release for token performance

**Comment by dushaniw** [comment]
Backporting feature for IS 6.1 related identity branches.

- [ ] Initial extension points for revocation, refresh grant - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2091

**Comment by tharikaGitHub** [comment]
Closing as the task is completed.
