### ISSUE TITLE
Fix Dashboard 4.2.0 issues

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#1699]
### Problem

Following issues are reported on WSO2 Monitoring Dashboard

- [ ] Unable to override the authorization endpoint when configuring SSO for MI dashboard - https://github.com/wso2/api-manager/issues/1525
- [ ] User list limitated by 1500 entries  - https://github.com/wso2/api-manager/issues/1674
- [ ] Faulty CAR Files are not listed in the Dashboard or over the CLI - https://github.com/wso2/api-manager/issues/1662

### Solution

-

### Affected Component

MIDashboard

### Version

4.x.x

**Comment by dulanjalidilmi** [comment]
Fixed: User list limited by 1500 entries issue: https://github.com/wso2/product-mi-tooling/pull/348

**Comment by dulanjalidilmi** [comment]
Fixed : Page Reload issue : https://github.com/wso2/product-mi-tooling/pull/349

**Comment by dulanjalidilmi** [comment]
Fixed : Faulty CAR Files are not listed in the Dashboard or over the CLI : https://github.com/wso2/product-mi-tooling/pull/350
Please find the sample preview attached.
<img width="1471" alt="Screenshot 2023-04-10 at 07 58 00" src="https://user-images.githubusercontent.com/38608578/230822643-de16787d-3060-489c-bf4f-7f5eb49a0a3f.png">

**Comment by dulanjalidilmi** [comment]
As per the code review, we have changed the FAULTY CAPP view as follows.
<img width="1448" alt="Screenshot 2023-04-13 at 18 33 21" src="https://user-images.githubusercontent.com/38608578/232374255-26ae335b-ebbe-4c3a-b71b-6a3a13c61099.png">
