### ISSUE TITLE
Migrating Tenant Configurations from the Registry

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/api-manager#194]
### Problem

Using the registry to change Tenant Configurations is not a user-friendly task.

### Solution

Migrating tenant configurations from registry and support managing through the admin portal

- Tenant Branding (custom theming, URLs, etc.)

- External devPortal Config

- Google Analytics Config

- Self Sign up Config

### Affected Component

APIM

**Comment by Avishka-Shamendra** [comment]
Hi all,

Will resume the following subtasks

#### Phase 1
- [ ] https://github.com/wso2/api-manager/issues/363
- [ ] https://github.com/wso2/api-manager/issues/362
- [ ] https://github.com/wso2/api-manager/issues/2201

**Comment by Avishka-Shamendra** [comment]
### Progress Update (26/27 Oct 2023)

- Conducted the design review and finalised the design for workflow, GA config migrations.
- Decided not to proceed with external API store migration and deprecate the feature.
- Started implementation on workflow migration.

**Comment by Avishka-Shamendra** [comment]
### Work Log (30 Oct - 3 Nov)

#### Completed
 - Changed the workflow config fetching way from registry to Advanced Configuration JSON file.
 - Facilitated default workflow config when the JSON schema is not provided in the Advanced Configuration.
 - Used new Workflows config format & facilitated different config options.
 - Removed of all uses of the existing `workflow-extensions.xml` file in carbon-apimgt.
 - Defined the new `Workflows` schema in `tenant-config-schema.json`.
 - Wrote/Modified tests related to workflow configs in carbon-apimgt.

#### Ongoing/Upcoming
- Writing/Modifying integration tests related to workflow configs in product-apim.
- Creating migration artefacts.

**Comment by Avishka-Shamendra** [comment]
### Work Log (6 Nov - 10 Nov)
 
#### Completed
 - Modified integration tests in product-apim to support new workflow configs.
 - Modified `tenant-config-schema.json` to support proper validation for workflow config.
 - Started work on APIM 5.x.x `migration-client` to support registry migration.

#### Ongoing/Upcoming

- Completed the work on migration resources.
- Conduct the code review.

**Comment by Avishka-Shamendra** [comment]
## Work Log (13 Nov - 17 Nov)

#### Completed

- Completed work on migration resources.
- Tested the migration to new workflow configuration from old xml configuration.
- Fixed several minor issues identified in the implementation.
- Refactored the code.
- Scheduled the code review.

#### Ongoing/Upcoming
- Conduct the code review.
- Do requested changes.

**Comment by Avishka-Shamendra** [comment]
## WorkLog ( 21 Nov -23 Nov )

#### Completed

- Conducted code review
- Completed requested changes
    -  Remove the enabled flag from workflow approvals. If someone wants to disable, they can remove the json element. If approval workflows, the value of the json field will be {}.
    -  Remove the XML parsing for the property value. Assume XML values are not used as property values in migrated setups. 
    - Make properties to allow only primitives. Restrict it from the schema as well.
    -  Support resolving secrets using securevault is similar to what we have done for notification endpoints in the IS KM connector. We cannot use the same function for XML.
    -   Make the default StateList properties hardcoded and change only if someone adds the property.
- Did required documentation changes
- Opened draft PRs as discussed in code review.

#### Ongoing/ Upcoming
- Start work on GA Config Migration

**Comment by Avishka-Shamendra** [comment]
## Work Log (11 Dec - 15 Dec)

### Started work on GA config Migration

**Completed:**
- Examined the existing GA configuration and observed its behavior.
- Finalized the JSON format for the new GA configuration.
- Eliminated the use of the `ga-config.xml` registry file.
- Implemented the DTO class.
- Adjusted the `GaConfigApiServiceImpl` to accommodate the new configuration format.
- Updated the `APIMgtGoogleAnalyticsTrackingHandler` class to support the new configuration format.
- Initiated testing with the modified codebase.

**Ongoing/Upcoming:**
- Continue testing and implement necessary changes to the codebase.
- Resolve issues related to detecting configuration changes when the server is running.
- Write/Modify unit/integration tests.

**Comment by Avishka-Shamendra** [comment]
Hi all,

Migrations of workflow config and GA config will not be included in the upcoming 4.x releases. Instead, they will be incorporated in future 5.x release.
