### ISSUE TITLE
Migrate workflow configuration to admin portal

### ISSUE THREAD

**Issue by Avishka-Shamendra** [wso2/api-manager#2201]
### Description

Currently workflows are configured through `workflow-extensions.xml` file in the carbon registry. The plan is to move these configuration to admin portal as part of the effort to move away from carbon registry.

### Affected Component

None

**Comment by Avishka-Shamendra** [comment]
## Sub-tasks Breakdown

- [ ] Change the workflow config fetching way from registry to Advanced Configuration JSON file.
- [ ] Facilitate default workflow config when the JSON schema is not provided in the Advanced Configuration.
- [ ] Use new `Workflows` config format & facilitate different config options.
- [ ] Removal of all uses of the existing workflow-extensions.xml file.
- [ ] Write/Modify unit/integration tests.
- [ ] Run & fix tests failures.
- [ ] Refactor code.
- [ ] Conduct code review.
- [ ] Perform requested changes.
- [ ] Documentation.
- [ ] Migration.
- [ ] UI Tests.

**Comment by Avishka-Shamendra** [comment]
Hi all,

Had the code review and following changes were suggested,

- Remove the enabled flag from workflow approvals. If someone wants to disable, they can remove the json element. If approval workflows, the value of the json field will be {}.
- Remove the XML parsing for the property value. Assume XML values are not used as property values in migrated setups. 
- Make properties to allow only primitives. Restrict it from the schema as well.
- Support resolving secrets using securevault is similar to what we have done for notification endpoints in the IS KM connector. We cannot use the same function for XML.
- Make the default StateList properties hardcoded and change only if some adds the property.
