### ISSUE TITLE
Redesign Traffic Manager and Event Hub on top of GRPC and remove thrift

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#227]
# Purpose

Currently communication from the Gateway to Traffic Manager and events from other components to the Event Hub is done via Thrift binary connections. The purpose of this implementation is to enable using gRPC instead of Thrift communication.
Problem
Thrift connections are implemented with HTTP 1.1 support. It does not support load balancing. Also opening connections for thrift in a kubernetes environment is not efficient. gRPC on the other hand is built with HTTP 2 support. It supports load balancing, language agnostic and much more efficient.

Communication to the Event Hub is infrequent but gateway to Traffic Manager communications are very frequent therefore efficiency is impactful.

# Solution
Implement gRPC communication where the Event Hub and Traffic Manager currently receive data from Thrift. This will provide better support with HTTP 2 for  kubernetes deployments, load balancing and increased efficiency are the benefits of addressing the problem.

# Affected Component 
APIM

# Version
4.2.0

# Implementation Details

First the traffic manager throttling events will be converted to gRPC. Then Event Hub communication will be implemented with gRPC. The complete breakdown is as follows.

# Tasks
- [x] #336
- [x] #337  
- [x] #414
- [x] #415
- [x] #417
- [ ] Complete the gRPC implementation with authentication 
- [ ] Implement gRPC throttle event publisher for the Traffic Manager communication 
- [ ] Implement gRPC throttle event receiver for the Traffic Manager communication     
- [ ] Implement failover and load balancing for Traffic Manager communication 
- [ ] Finalize Design for EventHub gRPC communication 
- [ ] Implement gRPC for the Event Hub communication 
- [ ] Test Implementation for Traffic Manager implementation 
- [ ] Test Implementation for Event hub implementation 
- [ ] Evaluate Migration impact 
- [ ] Doc changes for gRPC TM and Eventhub communication
