### ISSUE TITLE
Add Missing Custom Keystore J2 Mapping and Docs

### ISSUE THREAD

**Issue by Avishka-Shamendra** [wso2/api-manager#2449]
### Description

Up until APIM 3.2.0 we have provided the support to configure a custom keystore to sign the API Keys[1]. The `custom_keystore` configuration in [1] is mapped to `carbon.xml.j2` in the latest 3.2.0 pack. However, this mapping was not added to `wso2/carbon-kernel` repo's `carbon.xml.j2` file. Further, APIM 4.x.x docs are missing content of [1], though configuration-catalog contains `custom_keystore` config

### ToDo
- [x] Add `custom_keystore` j2 mapping to `wso2/carbon-kernel`  `4.9.x`
- [x]  Add missing docs as per [1]
- [x] Test on alpha

### j2 mapping

```
{% for key,keyStore in custom_keystore.items() %}
        <{{key}}>
            <!-- Keystore file location-->
            <Location>${carbon.home}/repository/resources/security/{{keyStore.file_name}}</Location>
            <!-- Keystore type (JKS/PKCS12 etc.)-->
            <Type>{{keyStore.type}}</Type>
            <!-- Keystore password-->
            <Password>{{keyStore.password}}</Password>
            <!-- Private Key alias-->
            <KeyAlias>{{keyStore.alias}}</KeyAlias>
            <!-- Private Key password-->
            <KeyPassword>{{keyStore.key_password}}</KeyPassword>
        </{{key}}>
{% endfor %}
```

[1] https://apim.docs.wso2.com/en/3.1.0/learn/api-security/api-authentication/secure-apis-using-api-keys/#configuring-custom-keystores

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.0.0, 4.1.0, 4.2.0

### Related Issues

https://github.com/wso2/product-apim/issues/8448

**Comment by Avishka-Shamendra** [comment]
Hi all,

Tested the functionality on alpha pack.

Thank you
Avishka
