### ISSUE TITLE
AI-powered API Chat for testing APIs using Natural Language

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#2849]
### Description

This issue is created to track the API Chat feature implementation.

- [x] Fix the Ballerina Agent codebase to cater to the on-prem usecase
- [x] Deploy Ballerina Agent in Choreo
- [x] Add backend REST APIs for API Chat feature
- [x] Add UI implementation for API Chat
- [x] Add documentation 

### Affected Component

APIM

### Version

4.3.0

**Comment by ashera96** [comment]
### Subtask
Add backend REST APIs for API Chat feature

- https://github.com/wso2/carbon-apimgt/pull/12357
- https://github.com/wso2/carbon-apimgt/pull/12360
- https://github.com/wso2/carbon-apimgt/pull/12374
- https://github.com/wso2/carbon-apimgt/pull/12385
- https://github.com/wso2/carbon-apimgt/pull/12392

**Comment by ashera96** [comment]
### Subtask

Add UI implementation for API Chat

- https://github.com/wso2/apim-apps/pull/626
- https://github.com/wso2/apim-apps/pull/642
- https://github.com/wso2/apim-apps/pull/657
- https://github.com/wso2/apim-apps/pull/661
- https://github.com/wso2/apim-apps/pull/663
- https://github.com/wso2/apim-apps/pull/671
- https://github.com/wso2/apim-apps/pull/674
- https://github.com/wso2/apim-apps/pull/675
- https://github.com/wso2/apim-apps/pull/679

**Comment by ashera96** [comment]
### Subtask

Add documentation

#### Related PRs

- https://github.com/wso2/docs-apim/pull/7789
- https://github.com/wso2/docs-apim/pull/7790
- https://github.com/wso2/docs-apim/pull/7932
- https://github.com/wso2/docs-apim/pull/7886
- https://github.com/wso2/docs-apim/pull/7937
- https://github.com/wso2/docs-apim/pull/7886
