### ISSUE TITLE
Intra-vendor Model Routing Support AI APIs

### ISSUE THREAD

**Issue by AnuGayan** [wso2/api-manager#3353]
### Problem

AI API designers need to be able to route incoming requests across models within a single vendor’s ecosystem.

With the API Manager 4.4.0 release, AI API support was introduced. We allow API consumers to specify the model they wish to consume within that LLM vendor. This leaves us with the following concerns:

- API designers have no control over which models are used, how frequently they are accessed, or the costs incurred.
- Risks such as model exhaustion and model misuse could lead to API being throttled out.
- Inability to enforce a model routing strategy at design time considering the use cases of AI applications consuming the API.

### Proposed Solution

Support intra-vendor model routing for AI APIs.

The proposed solution is to enforce the model routing strategy as a policy for the API request flow. Policies can be categorised as follows:
- Static routing techniques (only relies on the incoming request)
- Dynamic routing techniques (based on metrics from previous invocations)
- Failover
- Custom routing strategy enforcement

Targeting the APIM 4.5.0 release, we are shipping the following policies:
- Model Round-robin Policy
- Model Weighted Round-robin Policy
- Model Failover Policy

### Task Breakdown

- [x] Feature design and UI wireframes
- [x] Admin REST API changes for AI Vendor model list maintenance
- [x] Publisher REST API changes for multi-endpoint support
- [x] Revamp the existing flow to handle AI APIs via a separate velocity template
- [x] Onboard round-robin policy
- [x] Onboard failover policy
- [x] Admin UI changes to handle model list under the AI vendor
- [ ] Handle APICTL flows: import/export APIs with multiple endpoints
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] Write CTL tests
- [x] Write feature documentation

### Version

4.5.0

**Comment by ashera96** [comment]
### Progress Update:

The task breakdown under the issue description was updated with the completed tasks.

The following PRs were merged targeting the alpha release:
1. Carbon-apimgt changes: https://github.com/wso2/carbon-apimgt/pull/12871
2. Apim-apps changes: https://github.com/wso2/apim-apps/pull/883
3. Product-apim changes: https://github.com/wso2/product-apim/pull/13661

**Comment by ashera96** [comment]
### Progress Update:

The following PRs were merged targeting the beta release:
1. Carbon-apimgt changes: https://github.com/wso2/carbon-apimgt/pull/12987
2. Apim-apps changes: https://github.com/wso2/apim-apps/pull/929
3. Product-apim changes: https://github.com/wso2/product-apim/pull/13695
