### ISSUE TITLE
Migration of Self Sign up Config

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#361]
- [x] Changing the data fetching way from registry to DBMS(or Advanced Configuration JSON file). 
- [x] Removal of using the existing sign-up-config.xml files 
- [x] Code refactoring 
- [x] Facilitating self-sign-up when the JSON schema is not provided in the Advanced Configuration.

**Comment by thisaltennakoon** [comment]
**Sub-tasks Breakdown**

- Changing the data fetching way from registry to DBMS(or Advanced Configuration JSON file).

- Removal of using the existing sign-up-config.xml files

- Code refactoring

- Facilitating self-sign-up when the JSON schema is not provided in the Advanced Configuration.

**Comment by thisaltennakoon** [comment]
[Link to the Documentation](https://docs.google.com/document/d/1y8pRJbgtGfwV6vCKKOO-QA21f6gMY48KmESDPariQbc/edit?usp=sharing)
