### ISSUE TITLE
Google Analytics Config

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#362]

**Comment by Avishka-Shamendra** [comment]
## Description
Currently GA are configured through 'ga-config.xml` registry file. The plan is to move this configuration to admin portal's advanced configurations section as part of the effort to move away from carbon registry.

**Comment by Avishka-Shamendra** [comment]
### Subtasks

- [ ] Update codebase to fetch GA config from `tenant-conf.json` instead of registry.
- [ ] Remove `default-ga-config.xml` file and all uses of `ga-config.xml` file.
- [ ] Add new config schema to `tenant-config-schema.json`.
- [ ] Refactoring & testing. 
- [ ] Create migration resources.
- [ ] Documentation.
