### ISSUE TITLE
External devPortal Config

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#363]

**Comment by thisaltennakoon** [comment]
### Sub-tasks Breakdown

- [x] Changing the data fetching way from registry to DBMS(or Advanced Configuration JSON file).
- [x] Removal of using the existing default-external-api-stores.xmlfiles
- [x] Code refactoring
- [x] Facilitating to configure external devPortals when the JSON schema is not provided in the Advanced Configuration.

**Comment by Avishka-Shamendra** [comment]
## Description
The external API stores are currently configured through `external-api-stores.xml` file in the registry through the management console. The plan is to move this configuration to `tenant-conf.json` so that it can be configured through the admin portal.

**Comment by Avishka-Shamendra** [comment]
As per the internal discussions, decided not to proceed this migration as this feature will soon be deprecated.
