### ISSUE TITLE
Test Feature

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#403]
### Problem

Test

### Solution

test

### Affected Component

APIM

### Version

4.x.x

### Tasks

- [x] #404
- [ ] Finalize Feature Design
- [ ] Implement REST API changes
- [ ] Implement backend and DB changes 
- [ ] Implement integration tests
- [ ] Prepare feature  documentation
