### ISSUE TITLE
MI Dashboard Revamp and add Pagination and Search 

### ISSUE THREAD

**Issue by RusJaI** [wso2/api-manager#412]
### Problem

- Since there are many inconsistencies due to the database keeping in MI Dashboard, currently it requires many workarounds to in different scenarios
- Currently there's no search functionality in MI Dashboard to search the deployed artifacts
- Pagination need to be arranged, rather loading the entire list of items from backend

### Solution
Prior to implementing, have to decide whether to keep both database and management API invocations further or coming into a cleaner approach.

[UPDATE] After some discussions it was finalised to remove the database from MI Dashboard as a way to resolve the inconsistencies. With this change, it requires some changes in dashboard level in terms of fetching and storing the data.

Design and implement the pagination and search capabilities for MI dashboard.

### Affected Component

MIDashboard

### Version

4.0.1 and above

### Implementation

- [x] [Plan a solution for the current inconsistencies of MI dashboard](https://github.com/wso2/api-manager/issues/505)
- [x] [Prepare the design for the revamp in MI and the search and pagination feature](https://github.com/wso2/api-manager/issues/507)
- [x] [Remove database from MI dashboard](https://github.com/wso2/api-manager/issues/508)
- [x] [Add searching component to the UI](https://github.com/wso2/api-manager/issues/575)
- [x] [Implement search functionality](https://github.com/wso2/api-manager/issues/576)
- [x] [Implement Pagination ](https://github.com/wso2/api-manager/issues/577)
- [x] [Tests for the search and pagination](https://github.com/wso2/api-manager/issues/578)
- [x] [Update Documentation](https://github.com/wso2/api-manager/issues/579)

### Related Issues

https://github.com/wso2/micro-integrator/issues/2650
https://github.com/wso2-enterprise/wso2-apim-internal/issues/236
https://github.com/wso2/api-manager/issues/352
