### ISSUE TITLE
Improve the apim migration client to continue the rest of the migration step in case of error 

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#615]
### Problem

Currently when there is an error in a specific migration step in the APIM migration client, we stop the migration at that point instead of continuing. Therefore the rest of the migration step does not complete causing us to do a remigration. 

### Solution

This should be improved so that we continue the rest of the migration step in case of error and finally throw the respective exception.

### Affected Component

APIM

### Task List
- [x] #616
- [x] Need to improve 'updateAPIPropertyVisibility' flow
- [x] Need to improve 'UpdateGenericAPIArtifacts' flow
- [x] Need to improve 'updateAPITypeInDB' flow
- [x] Need to improve 'moveUUIDToDBFromRegistry' flow
- [x] Need to improve 'migrateWebSocketAPI' flow
- [x] Need to improve 'updateRegistryPathsOfIconAndWSDL' flow
- [x] Need to improve 'removeUnnecessaryFaultHandlers' flow
- [x] Need to improve 'migrateEndpointCertificates' flow

### Migration flows identified as 'not needed to be fixed'

- rxtMigration
- migrateFaultSequencesInRegistry
- addDefaultRoleCreationConfig
- updateScopeRoleMappings
- ScopeMigration
- spMigration
- migrateScopes
- migrateProductMappingTable
- replaceKMNamebyUUID

**Comment by msm1992** [comment]
- [ ] APIM Revision Related Migration: Here when an error occurs while creating/deploying a revision, we should log the error and continue revision related migration for the remaining AI/Product Artifacts.
